import { Metadata } from "next";
import { FC } from "react";

interface LayoutProps {
    children: any
}

export const metadata: Metadata = {
    title: "Create Auth App",
    description: "Generated by create next app",
};

const Layout: FC<LayoutProps> = ({ children }) => {
    return children;
};

export default Layout;
